plugins:
  orders_menu_enabled:
    default: true
    client: true
  orders_menu_url:
    type: string
    default: ""
    client: true
    description:
      zh_CN: "“我的订单”菜单点击跳转的链接，支持占位符 :username 与 :userid"
      en: "Target URL for 'My Orders'. Supports :username and :userid placeholders."
  orders_menu_label:
    type: string
    default: "我的订单"
    client: true
  orders_menu_icon:
    type: string
    default: "shopping-cart"
    client: true
  orders_menu_position:
    type: string
    default: "profile" # profile | user_menu | both
    client: true
  orders_menu_open_in_new_tab:
    type: bool
    default: true
    client: true
